language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
    # codeclimate test reporter
    - CC_TEST_REPORTER_ID=050baa19b6b5ce60a279840ea236e87781b2b4805c17f854ae78309d2d6e1293

before_script:
  - npm run build
script:
  - npm test
after_success:
  - npm run coverage